---
  - name: "cert-manager: create namespace"
    shell: kubectl create ns cert-manager --dry-run -o yaml | kubectl apply -f -

  - name: "cert-manager: add helm repository"
    shell: helm repo add jetstack https://charts.jetstack.io
    
  - name: "cert-manager: update repositories"
    shell: helm repo update

  - name: "cert-manager: install"
    shell: >
      helm upgrade -i cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --version {{ kubernetes_cert_manager_version }} \
      --set installCRDs=true

  # - name: "cert-manager: create directory"
  #   file:
  #     path: "{{ ansible_home_dir }}/cert-manager"
  #     state: directory
  
  # - name: "cert-manager: generate values file"
  #   template:
  #     src: clusterissuer.yaml.j2
  #     dest: "{{ ansible_home_dir }}/cert-manager/clusterissuer.yaml"
  #     mode: '0644'

  # - name: "cert-manager: wait to become available" 
  #   wait_for:
  #     timeout: 15
  #   delegate_to: localhost

  # - name: "cert-manager: create cluster issuer"
  #   shell: "kubectl apply -f {{ ansible_home_dir }}/cert-manager/clusterissuer.yaml"