---
  - name: "hetzner ccm: create hetzner cloud secret"
    shell: >
      kubectl create secret generic hcloud \
        -n kube-system\
        --from-literal=token={{ hetzner_cloud_token }} \
        --from-literal=network={{ hetzner_cloud_network }} \
        --dry-run -o yaml | kubectl apply -f -

  - name: "hetzner ccm: create deployment directory" 
    file:
      path: "{{ ansible_home_dir }}/hetzner/ccm"
      state: directory
  
  - name: "hetzner ccm: generate yaml file"
    template:
      src: hetzner_ccm.yaml.j2
      dest: "{{ ansible_home_dir }}/hetzner/ccm/full.yaml"
      mode: '0644'

  - name: "hetzner ccm: apply deployment file"
    shell: "kubectl apply -f {{ ansible_home_dir }}/hetzner/ccm/full.yaml"